### ISSUE TITLE
Incorrect failures reported using Team Engine 

### ISSUE THREAD

**Issue by lshipman** [opengeospatial/ets-gpkg10#11]
Using Team Engine to test a GeoPackage indicates that Requirement 1 and 2 are incorrect. Both are there and correct.

Requirement 1:
Using od -c simple.gpkg:
lance@JOTUNHEIMEN /cygdrive/c/temp
$ od -c simple.gpkg | more
0000000   S   Q   L   i   t   e       f   o   r   m   a   t       3  \0

Requirement 2:
C:\temp>sqlite3 simple.gpkg
SQLite version 3.8.7.4 2014-12-09 01:34:36
Enter ".help" for usage hints.
sqlite> pragma application_id;
1196437808
sqlite> .quit

Example GeoPackage:
[simple.zip](https://github.com/opengeospatial/ets-gpkg10/files/431235/simple.zip)

**Comment by moran0013** [comment]
Passes both tests when run locally. Looking into causes it would fail in the web harness.

**Comment by moran0013** [comment]
the teamengine web app seems to fail when calling assertequals on two byte arrays. I put in a workaround, still chasing down why that would fail.

**Comment by lshipman** [comment]
Just tried the teamengine web app and it still returns the same failures. When will the fix take effect?

**Comment by bermud** [comment]
@lshipman, we will have a new revision in beta by Friday. Thanks for reporting.
