### ISSUE TITLE
Incorrect failures reported  on data type

### ISSUE THREAD

**Issue by fhoubie** [opengeospatial/ets-gpkg10#19]
Invalid data type: MultiPolygon in table states. As far as I can see MultiPolygon is in the list of supported Geometries. Test file can be accessed here : https://www.dropbox.com/s/cwd519lso7irjak/states.gpkg?dl=0

**Comment by moran0013** [comment]
fix uploaded. test relaxed to accept different cases in the column type (it was looking for MULTIPOLYGON and getting MultiPolygon, which would fail).

**Comment by moran0013** [comment]
Scratch that. Although Features is not yet implemented, Req. 25 states that "The geometry_type_name value in a gpkg_geometry_columns row SHALL be one of the uppercase geometry type names specified in Geometry Types (Normative)." With that in mind the fix isn't going to be accepted, the data needs to have MULTIPOLYGON as the type. 

(my apologies for the confusion)

**Comment by fhoubie** [comment]
Thanks a lot for the explanation.

2016-09-08 20:36 GMT+02:00 moran0013 notifications@github.com:
