### ISSUE TITLE
Column definitions are incorrectly marked as unique

### ISSUE THREAD

**Issue by abucklecslt** [opengeospatial/ets-gpkg10#21]
Class TableVerifier method getUniques() needs to consider the unique column when executing the PRAGMA index_list() method.  getUniques() method is currently returning both unique and non unique columns. A possible fix is as follows:

//Only consider columns that has a unique flag set to 1.

```
private static Set<UniqueDefinition> getUniques(){
...
final String indexName = indices.getString("name");
int unique = indices.getInt("unique");

 if(unique > 0){
......
 `names.add(namesSet.getString("name"));`
......
}
...
}
```

Our geopackage is currently failing test tilesTableDefinitions (See OGC 12-128r12: Requirement 54). Our tiles table contains non-unique indexes, which is causing our gpkg to fail the test.

**Comment by moran0013** [comment]
do you have a sample geopackage to reproduce the error with?

**Comment by abucklecslt** [comment]
Here is a sample geopackage to reproduce the error (See OGC 12-128r12: Requirement 54). I removed some of the tiles to make the file smaller.

Cheers;

[ERDC_Whitehorse_GeoPackage.gpkg.zip](https://github.com/opengeospatial/ets-gpkg10/files/467158/ERDC_Whitehorse_GeoPackage.gpkg.zip)

**Comment by LukeL-dev** [comment]
I've pushed a fix. Please let me know if this resolves the issue for you.

**Comment by abucklecslt** [comment]
I just tested your fix with some of our geopackages. The fix works. Thank you.
