### ISSUE TITLE
Test on default value of last_changed column should be flexible

### ISSUE THREAD

**Issue by fhoubie** [opengeospatial/ets-gpkg10#22]
The test on the default value of the last_changed field is done on 
strftime('%Y-%m-%dT%H:%M:%fZ','now')

We have used 
strftime('%Y-%m-%dT%H:%M:%fZ',CURRENT_TIMESTAMP)

which is equivalent, but the test fails. The test should test on both values .

**Comment by LukeL-dev** [comment]
Equivalence is what's being tested. Please refer to https://github.com/opengeospatial/ets-gpkg10/blob/master/src/main/java/org/opengis/cite/gpkg10/TableVerifier.java#L130 which calls the method checkExpressionEquivalence(...) defined here: https://github.com/opengeospatial/ets-gpkg10/blob/master/src/main/java/org/opengis/cite/gpkg10/TableVerifier.java#L144

SQLite appears to treat 'now' and CURRENT_TIMESTAMP differently. Try running this command in sqlite:

`SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ',CURRENT_TIMESTAMP);`

I've tested with three different SQLite implementations, and I always get a similar result to:
`"2016-09-15T12:38:08.269Z" "2016-09-15T12:38:08.000Z"`

CURRENT_TIMESTAMP only provides second accuracy, while 'now' provides sub-second accuracy. I can't say why that is, but the result is that 'now' and CURRENT_TIMESTAMP are not equivalent. The GeoPackage spec has chosen to go with 'now', and the tests reflect that choice.

**Comment by fhoubie** [comment]
Thanks a lot for feedback, you can then ignore this request.

**Comment by LukeL-dev** [comment]
My pleasure. I was surprised to find there was any difference between the two. I wish I had a better explanation, but the SQLite documentation doesn't provide any insight in this case.
