### ISSUE TITLE
What version of the standard is being used in the tests?

### ISSUE THREAD

**Issue by lshipman** [opengeospatial/ets-gpkg10#23]
The document at http://cite.opengeospatial.org/te2/about/gpkg10/1.0/site/ implies that the tests are against the 1.0 version of the standard, but the version of the standard referenced (http://www.geopackage.org/spec/) is the 1.1-SNAPSHOT.

**Comment by LukeL-dev** [comment]
At the time the tests were written, I believe the current standard (pointed to by the above URL) was 1.0.2.

**Comment by bermud** [comment]
@LLambertRGi  is correct. We have already an issue opened related to updating the test to 1.1.
https://github.com/opengeospatial/ets-gpkg10/issues/4
