### ISSUE TITLE
Update link on site/index to reference the correct specification

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg10#24]
In the index page:

> This conformance test suite verifies the structure and content of a GeoPackage 1.0 data container. The GeoPackage specification ...

The link to the specification points  to http://www.geopackage.org/spec/

It should be:
http://www.opengis.net/doc/IS/geopackage/1.0

**Comment by LukeL-dev** [comment]
I've pushed a change to the README.md to reflect the correct URL.
