### ISSUE TITLE
Content-Type header expected in geopackage response

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-gpkg10#25]
The `URIUtils::dereferenceURI` method is called to fetch the geopackage to be validated. A Content-Type header is expected in the response message, but this is not strictly required according to [RFC 7231](http://httpwg.org/specs/rfc7231.html#header.content-type).

A `NullPointerException` is thrown if the header is missing, If the header is not present, just assume it is "application/octet-stream".

**Comment by bermud** [comment]
@rjmartell, will this issue be present in other TestNG tests that use URIUtils::dereferenceURI?
