### ISSUE TITLE
Clarify status of this ETS

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gpkg10#36]
As described in https://opengeospatial.github.io/ets-gpkg12/ the ETS GeoPackage 1.2 supports also GeoPackage 1.0 (and 1.1). 

Is the scope of the tests in ETS GeoPackage 1.2 for GeoPackage 1.0 the same as in this ETS? Then this repository  can be removed (if version 1.0 of ETS GeoPackage 1.2 is available) or at least be marked as obsolete.

**Comment by lgoltz** [comment]
See also https://github.com/opengeospatial/ets-gpkg12/issues/58

**Comment by ghobona** [comment]
ets-gpkg10 remains the official ETS for testing for GeoPackage 1.0 compliance.
