### ISSUE TITLE
Master not building 

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg10#8]
Commit d6a054f8ae2d7664e9a7c3315ec5a54201e530d7 is not building.

Here is the error:

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.524 sec <<< FAILURE! - in org.opengis.cite.gpkg10.VerifyTestNGController
cleanTestRun(org.opengis.cite.gpkg10.VerifyTestNGController)  Time elapsed: 0.523 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected number of fail verdicts. expected:<2> but was:<1>
    at org.opengis.cite.gpkg10.VerifyTestNGController.cleanTestRun(VerifyTestNGController.java:62)

**Comment by LukeL-dev** [comment]
I'm not clear on what the issue is. Does a test fail that should not, or does the code not build? It builds locally, but the error you've posted seems to suggest a test has failed. Do you have any further detail, or can you provide the .gpkg that's being tested with?

**Comment by bermud** [comment]
I'm not giving any .gpkg file. I'm just running `mvn clean install`. I think the test is using the files under the test/resources folder,

**Comment by bermud** [comment]
@LLambertRGi, have you had time to look into this? I would like to include this test in the next release of the OGC validation tools, which is happening early this week. Thank you!

**Comment by moran0013** [comment]
Its being worked right now. a test file is being changed mid-test, and we are trying to chase down where it's happening. update will _hopefully_ be today.

**Comment by bermud** [comment]
Fixed with #9. Thank you @moran0013.
